# ===== Simulation =====
dt=0.01
totalTime=90.0
numDrones=4

# ===== Physical =====
mass=2
kd=0.75
Ix=0.02
Iy=0.02
Iz=0.04

# ===== Control Gains =====
kp=3.5
kdCtrl=2.5
kR=8.5
kOmega=0.15

# ===== Formation & Collision =====
formKp=0.1
formKv=0.5
kRep=1
minSafeDistance=1

# ===== Communication =====
commRange=50.0
packetLoss=0.01

# ===== Environment =====
envWidth=100.0
envHeight=100.0
envDepth=1000.0

# ===== Logging =====
positionsCsv=Positions.csv
metricsTxt=Metrics.txt
